### ISSUE TITLE
Use jMonkeyEngine to render models

### ISSUE THREAD

**Issue by garyttierney** [apollo-rsps/Vicis#4]
Adopt jMonkeyEngine as the 3D scenegraph to avoid complexities involved in using OpenGL or other rendering APIs directly.  Using JavaFX's own 3D capabilities could be explored, however at first glance it seems too restrictive.

**Comment by tlf30** [comment]
I have used jMonkeyEngine for several projects. It is great.

**Comment by garyttierney** [comment]
I don't think there's many alternatives outside of building our own renderer.  I'd rather not go down that rabbit hole and be able to create something for this pretty quickly, so JME will do.
